#ifndef HAUSAUFGABE_02_NEWTONRAPHSONALGORITHM_H
#define HAUSAUFGABE_02_NEWTONRAPHSONALGORITHM_H
void newtonRaphsonMethod(double x, char selectedDerivation);
#endif //HAUSAUFGABE_02_NEWTONRAPHSONALGORITHM_H
